# Site settings
title: Anthony Ross' Blog
email: anthony.s.ross@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site dedicated to a number of ah-ha moments while programming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "allcentury.github.io" # the base hostname & protocol for your site
twitter_username: anthonysross
github_username:  allcentury

# Build settings
markdown: kramdown
